permalink: /:year/:month/:day/:title.html
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: chiyiw
  email: wp941019@126.com
  link: http://chiyiw.github.io
  weibo: http://weibo.com/iFlower
  github: http://github.com/chiyiw

# 站点信息
title: chiyiw's blog
description: chiyiw's博客
url: http://chiyiw.github.io
rss_url: /pages/atom.xml

#多说配置
duoshuo_short_name: gitcafechiyiw

#Google站内搜索
google_cx: g***

# avatar头像及Favicon
avatar: http://cdn.saymagic.cn/140830131806.png
favicon: http://cdn.saymagic.cn/140830131806.png
